version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # - npm install -g npm@latest
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -la dist

artifacts:
  files:
    - package.json
    - package-lock.json
    - dist/**/*
    - node_modules/**/*

cache:
  paths:
    - ./node_modules/**/*