version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
    pre_build:
      - npm install -g npm@latest
      - npm install
      - npm install core-util-is
    build:
      - npm run build

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
  base-directory: '.'
