version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # - npm install -g npm@latest
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp package.json dist
      - cp -a node_modules dist
      - ls -la dist

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes

cache:
  paths:
    - ./node_modules/**/*